#!/bin/csh -f
#
# Quick analysis of a set of cml files.
# Once all of your society's .cml files are in the current
# directory, run this script.  A perfect run has outQ+ == deliv.
#

# <copyright>
#  Copyright 2001 BBNT Solutions, LLC
#  under sponsorship of the Defense Advanced Research Projects Agency (DARPA).
# 
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the Cougaar Open Source License as published by
#  DARPA on the Cougaar Open Source Website (www.cougaar.org).
# 
#  THE COUGAAR SOFTWARE AND ANY DERIVATIVE SUPPLIED BY LICENSOR IS
#  PROVIDED 'AS IS' WITHOUT WARRANTIES OF ANY KIND, WHETHER EXPRESS OR
#  IMPLIED, INCLUDING (BUT NOT LIMITED TO) ALL IMPLIED WARRANTIES OF
#  MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE, AND WITHOUT
#  ANY WARRANTIES AS TO NON-INFRINGEMENT.  IN NO EVENT SHALL COPYRIGHT
#  HOLDER BE LIABLE FOR ANY DIRECT, SPECIAL, INDIRECT OR CONSEQUENTIAL
#  DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE OF DATA OR PROFITS,
#  TORTIOUS CONDUCT, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
#  PERFORMANCE OF THE COUGAAR SOFTWARE.
# </copyright>


set all="/tmp/$$.cml"
cat *.cml > $all
set out1 = `grep outQ+ $all | wc -l`
set out2 = `grep outQ- $all | wc -l`
set dom = `grep DOM $all | wc -l`
set lookup = `grep lookup $all | wc -l`
set before = `grep before $all | wc -l`
set sent = `grep sent $all | wc -l`
set error = `grep error $all | wc -l`
set retry = `grep retry $all | wc -l`
set in0 = `grep inQ0 $all | wc -l`
set in1 = `grep inQ+ $all | wc -l`
set in2 = `grep inQ- $all | wc -l`
set deliv = `grep deliv $all | wc -l`
set fail = `grep Fail $all | wc -l`

rm $all

echo outQ+ $out1
echo outQ- $out2
echo DOM $dom
echo lookup $lookup
echo before $before
echo sent $sent
echo error $error
echo retry $retry
echo inQ0 $in0
echo inQ+ $in1
echo inQ- $in2
echo deliv $deliv
echo Fail $fail
