#!/usr/bin/perl
# -*- Perl -*-

# makes the following changes:
# ocd.glm.asset -> ocd.glm.ldm.asset
# ocd.glm.lps -> ocd.glm.ldm.lps
# ocd.glm.plan -> ocd.glm.ldm.plan
# ocd.glm.oplan -> ocd.glm.ldm.oplan
# ocd.glm.policy -> ocd.glm.ldm.policy
# ocd.glm.plugin -> ocd.glm.ldm.plugins
# ocd.glm.ALPFactory - > ocd.glm.ldm.ALPFactory
# ocd.glm.ALPDomain - > ocd.glm.ldm.ALPDomain
# ocd.glm.Constants - > ocd.glm.ldm.Constants

$tmp = "/tmp/reorgglm.$$";

while (<>) {
  chop;
  $file = $_;
  print STDERR "$file";
  
  $found = 0;
  open(IN, "<$file");
  unlink($tmp);
  open(OUT, ">$tmp");
  while (<IN>) {
    # make sure that we re-split the glm package imports
    if (/import org\.cougaar\.domain\.glm\.\*;/) {
      print OUT "import org.cougaar.domain.glm.ldm.\*;";
      $found++;
    }

    s/package=org\/cougaar\/domain\/glm\/asset/package=org\/cougaar\/domain\/glm\/ldm\/asset/ && $found++;
    s/package=org\.cougaar\.domain\.glm\.asset/package=org\.cougaar\.domain\.glm\.ldm\.asset/ && $found++;

    # move these to ldm
    s/org\.cougaar\.domain\.glm\.ALPFactory/org\.cougaar\.domain\.glm\.ldm\.ALPFactory/g && $found++;
    s/org\.cougaar\.domain\.glm\.ALPDomain/org\.cougaar\.domain\.glm\.ldm\.ALPDomain/g && $found++;
    s/org\.cougaar\.domain\.glm\.Constants/org\.cougaar\.domain\.glm\.ldm\.Constants/g && $found++;
    
    # leave util in glm\.util
    
    # move asset* to ldm\.asset
    s/org\.cougaar\.domain\.glm\.asset/org\.cougaar\.domain\.glm\.ldm\.asset/g && $found++;
    
    # move the following packages aroung
    s/org\.cougaar\.domain\.glm\.lps/org\.cougaar\.domain\.glm\.ldm\.lps/g && $found++;
    s/org\.cougaar\.domain\.glm\.plan/org\.cougaar\.domain\.glm\.ldm\.plan/g && $found++;
    s/org\.cougaar\.domain\.glm\.oplan/org\.cougaar\.domain\.glm\.ldm\.oplan/g && $found++;
    s/org\.cougaar\.domain\.glm\.policy/org\.cougaar\.domain\.glm\.ldm\.policy/g && $found++;
    
    # move plugin to plugins
    s/org\.cougaar\.domain\.glm\.plugin\.OplanObserverPlugIn/org\.cougaar\.domain\.glm\.plugins\.OplanObserverPlugIn/g && $found++;
    print OUT $_;
  }
  close(OUT);
  close(IN);

  print STDERR "\t$found\n";
  if ($found) {
    # made changes

    unlink($file);
    open(IN, "<$tmp");
    open(OUT, ">$file");
    while(<IN>)  {
      print OUT "$_";
    }
    close(OUT);
    close(IN);
  }
}

unlink($tmp);


