/* 
 * <copyright>
 * Copyright 2002 BBNT Solutions, LLC
 * under sponsorship of the Defense Advanced Research Projects Agency (DARPA).

 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the Cougaar Open Source License as published by
 * DARPA on the Cougaar Open Source Website (www.cougaar.org).

 * THE COUGAAR SOFTWARE AND ANY DERIVATIVE SUPPLIED BY LICENSOR IS
 * PROVIDED 'AS IS' WITHOUT WARRANTIES OF ANY KIND, WHETHER EXPRESS OR
 * IMPLIED, INCLUDING (BUT NOT LIMITED TO) ALL IMPLIED WARRANTIES OF
 * MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE, AND WITHOUT
 * ANY WARRANTIES AS TO NON-INFRINGEMENT.  IN NO EVENT SHALL COPYRIGHT
 * HOLDER BE LIABLE FOR ANY DIRECT, SPECIAL, INDIRECT OR CONSEQUENTIAL
 * DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE OF DATA OR PROFITS,
 * TORTIOUS CONDUCT, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
 * PERFORMANCE OF THE COUGAAR SOFTWARE.
 * </copyright>
 */
package org.cougaar.core.mobility.ldm;

import org.cougaar.core.domain.LDMServesPlugin;
import org.cougaar.core.agent.ClusterContext;

import org.cougaar.core.mobility.Ticket;
import org.cougaar.core.mts.MessageAddress;
import org.cougaar.core.service.UIDServer;
import org.cougaar.core.util.UID;

/**
 * Package-private factory implementation.
 */
class MobilityFactoryImpl implements MobilityFactory {

  private MessageAddress self;
  private UIDServer uidServer;

  public MobilityFactoryImpl(LDMServesPlugin ldm) {
    self = ldm.getClusterIdentifier();
    uidServer = ((ClusterContext) ldm).getUIDServer();
  }

  public Object createTicketIdentifier() {
    UID uid = uidServer.nextUID();
    return new TicketIdentifier(uid);
  }

  public MoveAgent createMoveAgent(Ticket ticket) {
    Object tid = ticket.getIdentifier();
    if (!(tid instanceof TicketIdentifier)) {
      throw new IllegalArgumentException(
          "The ticket must have a \"getIdentifier()\""+
          " that was generated by this MobilityFactory's"+
          " \"createTicketIdentifier()\"");
    }
    UID uid = ((TicketIdentifier) tid).getUID();
    MessageAddress mobileAgent = ticket.getMobileAgent();
    if ((mobileAgent == null) ||
        (mobileAgent.equals(self))) {
      // local request
      return new LocalMoveAgentImpl(uid, self, ticket);
    } else {
      // remote request
      return new RemoteMoveAgentImpl(uid, self, ticket);
    }
  }

}
