/*
 * <copyright>
 * Copyright 1997-2001 Defense Advanced Research Projects
 * Agency (DARPA) and ALPINE (a BBN Technologies (BBN) and
 * Raytheon Systems Company (RSC) Consortium).
 * This software to be used only in accordance with the
 * COUGAAR licence agreement.
 * </copyright>
 */
// Stub class generated by rmic, do not edit.
// Contents subject to change without notice.

package org.cougaar.core.society.rmi;

public final class MTImpl_Stub
    extends java.rmi.server.RemoteStub
    implements org.cougaar.core.society.rmi.MT, java.rmi.Remote
{
    private static final long serialVersionUID = 2;
    
    private static java.lang.reflect.Method $method_getMessageAddress_0;
    private static java.lang.reflect.Method $method_receiveMessage_1;
    
    static {
	try {
	    $method_getMessageAddress_0 = org.cougaar.core.society.rmi.MT.class.getMethod("getMessageAddress", new java.lang.Class[] {});
	    $method_receiveMessage_1 = org.cougaar.core.society.rmi.MT.class.getMethod("receiveMessage", new java.lang.Class[] {org.cougaar.core.society.Message.class});
	} catch (java.lang.NoSuchMethodException e) {
	    throw new java.lang.NoSuchMethodError(
		"stub class initialization failed");
	}
    }
    
    // constructors
    public MTImpl_Stub(java.rmi.server.RemoteRef ref) {
	super(ref);
    }
    
    // methods from remote interfaces
    
    // implementation of getMessageAddress()
    public org.cougaar.core.society.MessageAddress getMessageAddress()
	throws java.rmi.RemoteException
    {
	try {
	    Object $result = ref.invoke(this, $method_getMessageAddress_0, null, -3927034548767378042L);
	    return ((org.cougaar.core.society.MessageAddress) $result);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
    
    // implementation of receiveMessage(Message)
    public void receiveMessage(org.cougaar.core.society.Message $param_Message_1)
	throws java.rmi.RemoteException
    {
	try {
	    ref.invoke(this, $method_receiveMessage_1, new java.lang.Object[] {$param_Message_1}, -2674303520185462339L);
	} catch (java.lang.RuntimeException e) {
	    throw e;
	} catch (java.rmi.RemoteException e) {
	    throw e;
	} catch (java.lang.Exception e) {
	    throw new java.rmi.UnexpectedException("undeclared checked exception", e);
	}
    }
}
