// Skeleton class generated by rmic, do not edit.
// Contents subject to change without notice.

package org.cougaar.core.society.rmi;

public final class MTImpl_Skel
    implements java.rmi.server.Skeleton
{
    private static final java.rmi.server.Operation[] operations = {
	new java.rmi.server.Operation("org.cougaar.core.society.MessageAddress getMessageAddress()"),
	new java.rmi.server.Operation("void receiveMessage(org.cougaar.core.society.Message)")
    };
    
    private static final long interfaceHash = 8364135813022741692L;
    
    public java.rmi.server.Operation[] getOperations() {
	return (java.rmi.server.Operation[]) operations.clone();
    }
    
    public void dispatch(java.rmi.Remote obj, java.rmi.server.RemoteCall call, int opnum, long hash)
	throws java.lang.Exception
    {
	if (opnum < 0) {
	    if (hash == -7855622025300351698L) {
		opnum = 0;
	    } else if (hash == 7057233312839370813L) {
		opnum = 1;
	    } else {
		throw new java.rmi.UnmarshalException("invalid method hash");
	    }
	} else {
	    if (hash != interfaceHash)
		throw new java.rmi.server.SkeletonMismatchException("interface hash mismatch");
	}
	
	org.cougaar.core.society.rmi.MTImpl server = (org.cougaar.core.society.rmi.MTImpl) obj;
	switch (opnum) {
	case 0: // getMessageAddress()
	{
	    call.releaseInputStream();
	    org.cougaar.core.society.MessageAddress $result = server.getMessageAddress();
	    try {
		java.io.ObjectOutput out = call.getResultStream(true);
		out.writeObject($result);
	    } catch (java.io.IOException e) {
		throw new java.rmi.MarshalException("error marshalling return", e);
	    }
	    break;
	}
	    
	case 1: // receiveMessage(Message)
	{
	    org.cougaar.core.society.Message $param_Message_1;
	    try {
		java.io.ObjectInput in = call.getInputStream();
		$param_Message_1 = (org.cougaar.core.society.Message) in.readObject();
	    } catch (java.io.IOException e) {
		throw new java.rmi.UnmarshalException("error unmarshalling arguments", e);
	    } catch (java.lang.ClassNotFoundException e) {
		throw new java.rmi.UnmarshalException("error unmarshalling arguments", e);
	    } finally {
		call.releaseInputStream();
	    }
	    server.receiveMessage($param_Message_1);
	    try {
		call.getResultStream(true);
	    } catch (java.io.IOException e) {
		throw new java.rmi.MarshalException("error marshalling return", e);
	    }
	    break;
	}
	    
	default:
	    throw new java.rmi.UnmarshalException("invalid method number");
	}
    }
}
