#!/usr/bin/perl
# -*- Perl -*-

# update references to LdmFactory to avoid deprecation warnings and
# later breakage.

# usage:
# refactory `find sourcetree -name "*.java" -print`

$tmp = "/tmp/repackage2.$$";

while ($file = shift) {
  $found = 0;
  open(IN, "<$file");
  unlink($tmp);
  open(OUT, ">$tmp");
  while (<IN>) {
    # change the accessor
    if (/getLdmFactory/) {
      $found = 1;
      s/getLdmFactory/getFactory/g;
    }
    # change the class and references
    if (/LdmFactory/) {
      $found = 1;
      s/LdmFactory/RootFactory/g;
    }
    print OUT $_;
  }
  close(OUT);
  close(IN);

  if ($found) {
    # made changes
    print "Fixing $file";
    unlink($file);
    open(IN, "<$tmp");
    open(OUT, ">$file");
    while(<IN>)  {
      print OUT "$_";
    }
    close(OUT);
    close(IN);
    print ".\n";
  }
}

unlink($tmp);

