#!/usr/bin/perl
# -*- Perl -*-

# update references to LdmFactory to avoid deprecation warnings and
# later breakage.

# usage:
# unjgl `find sourcetree -name "*.java" -print`

$tmp = "/tmp/unjgl.$$";

while ($file = shift) {
  $found = 0;
  open(IN, "<$file");
  unlink($tmp);
  open(OUT, ">$tmp");
  while (<IN>) {
    # fix unarypredicates
    $found += (s/com\.objectspace\.jgl\.UnaryPredicate/alp\.util\.UnaryPredicate/g);
    $found += (s/ContainerSubscription/CollectionSubscription/g);
    $found += (s/getContainer/getCollection/g);

    print OUT $_;
  }
  close(OUT);
  close(IN);

  if ($found) {
    # made changes
    print "Fixing $file";
    unlink($file);
    open(IN, "<$tmp");
    open(OUT, ">$file");
    while(<IN>)  {
      print OUT "$_";
    }
    close(OUT);
    close(IN);
    print ".\n";
  }
}

unlink($tmp);

