#!/bin/csh -f
#
# Quick analysis of a set of cml files.
# Once all of your society's .cml files are in the current
# directory, run this script.  A perfect run has outQ+ == deliv.
#

# <copyright>
#  
#  Copyright 2001-2004 BBNT Solutions, LLC
#  under sponsorship of the Defense Advanced Research Projects
#  Agency (DARPA).
# 
#  You can redistribute this software and/or modify it under the
#  terms of the Cougaar Open Source License as published on the
#  Cougaar Open Source Website (www.cougaar.org).
# 
#  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
#  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
#  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
#  A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
#  OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
#  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
#  LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
#  DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
#  THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
#  (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
#  OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#  
# </copyright>


set all="/tmp/$$.cml"
cat *.cml > $all
set out1 = `grep outQ+ $all | wc -l`
set out2 = `grep outQ- $all | wc -l`
set dom = `grep DOM $all | wc -l`
set lookup = `grep lookup $all | wc -l`
set before = `grep before $all | wc -l`
set sent = `grep sent $all | wc -l`
set error = `grep error $all | wc -l`
set retry = `grep retry $all | wc -l`
set in0 = `grep inQ0 $all | wc -l`
set in1 = `grep inQ+ $all | wc -l`
set in2 = `grep inQ- $all | wc -l`
set deliv = `grep deliv $all | wc -l`
set fail = `grep Fail $all | wc -l`

rm $all

echo outQ+ $out1
echo outQ- $out2
echo DOM $dom
echo lookup $lookup
echo before $before
echo sent $sent
echo error $error
echo retry $retry
echo inQ0 $in0
echo inQ+ $in1
echo inQ- $in2
echo deliv $deliv
echo Fail $fail
